using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace IcqBotNetCore.BusinessObjects.Commands
{
    [DataContract]
    public enum ParamTypeEnum
    {
        notDefined,
        about,
        addedBy,
        admins,
        bold,
        callbackData,
        caption,
        chat,
        chatId,
        code,
        creator,
        description,
        editedTimestamp,
        eventId,
        events,
        fileId,
        filename,
        firstName,
        format,
        forwardChatId,
        forwardMsgId,
        from,
        inlineKeyboardMarkup,
        inline_code,
        isBot,
        italic,
        language,
        lastEventId,
        lastName,
        length,
        link,
        mention,
        msgId,
        newMembers,
        nick,
        offset,
        ok,
        ordered_list,
        parseMode,
        parts,
        payload,
        photo,
        pollTime,
        pre,
        quote,
        removedBy,
        replyMsgId,
        showAlert,
        size,
        strikethrough,
        style,
        text,
        timestamp,
        title,
        token,
        type,
        underline,
        unordered_list,
        url,
        userId,
        RequestUri
    }
}
